// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK3aCeJT8oX6TKwsKHOkm6S9J9eCYjfyY',
    appId: '1:1018069072111:web:a45ef499efefd6d698431a',
    messagingSenderId: '1018069072111',
    projectId: 'dev-hub-task',
    authDomain: 'dev-hub-task.firebaseapp.com',
    storageBucket: 'dev-hub-task.firebasestorage.app',
    measurementId: 'G-9GSEQ8TFMF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-j5gXcrJj1vzxXfZeQcSEX9s41uOX2tk',
    appId: '1:1018069072111:android:4eb4aa4406cdea0f98431a',
    messagingSenderId: '1018069072111',
    projectId: 'dev-hub-task',
    storageBucket: 'dev-hub-task.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe4H_GdShxaGAQyov5inuwKqDo4hjfytc',
    appId: '1:1018069072111:ios:176111aa27657a5b98431a',
    messagingSenderId: '1018069072111',
    projectId: 'dev-hub-task',
    storageBucket: 'dev-hub-task.firebasestorage.app',
    iosBundleId: 'com.example.devHupTaskWeek1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe4H_GdShxaGAQyov5inuwKqDo4hjfytc',
    appId: '1:1018069072111:ios:176111aa27657a5b98431a',
    messagingSenderId: '1018069072111',
    projectId: 'dev-hub-task',
    storageBucket: 'dev-hub-task.firebasestorage.app',
    iosBundleId: 'com.example.devHupTaskWeek1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAK3aCeJT8oX6TKwsKHOkm6S9J9eCYjfyY',
    appId: '1:1018069072111:web:fd5a7fa989b47ed398431a',
    messagingSenderId: '1018069072111',
    projectId: 'dev-hub-task',
    authDomain: 'dev-hub-task.firebaseapp.com',
    storageBucket: 'dev-hub-task.firebasestorage.app',
    measurementId: 'G-M83W7Q0M93',
  );
}
